sudo: required
language: rust

# Dependencies of the web-view library.
addons:
  apt:
    packages:
      - libwebkit2gtk-4.0-dev
    sources:
      - sourceline: 'ppa:webkit-team/ppa'

cache:
  cargo: true
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - nvm install 8

install:
  - rustup component add rustfmt-preview
  - rustfmt --version
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn test --ci
  - cargo fmt -- --check
  - cargo test
