sudo: false
language: rust

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

cache: cargo

install:
  - rustfmt --version || cargo install rustfmt --version=0.9.0 --force
  - cargo install cargo-travis || true

script:
  - cargo fmt -- --write-mode=diff
  - cargo test

after_success:
  - cargo coveralls
