sudo: required
language: rust

# Dependencies of kcov, used by cargo-travis, and of the web-view library.
addons:
  apt:
    packages:
      - libssl-dev
      - libwebkit2gtk-4.0-dev
    sources:
      - sourceline: 'ppa:webkit-team/ppa'

cache:
  cargo: true
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - nvm install 8

install:
  - rustup component add rustfmt-preview
  - rustfmt --version
  - |
    if [[ $(cargo tarpaulin --version) != *0.6.1 ]]
    then
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force --version 0.6.1 cargo-tarpaulin
    fi
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn test --ci
  - cargo fmt -- --write-mode=diff
  - cargo test
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
