[package]
name = "yore"
version = "0.1.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
#serde-xml-rs = "0.1.2" # Requires Serde v0.9
