[package]
name = "yore"
version = "1.0.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
license = "MIT"

[dependencies]
chrono = "0.4"
clap = "2"
memmap = "0.6"
kamadak-exif = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
walkdir = "2"

[dev-dependencies]
tempdir = "0.3"
